# Generated by Django 4.2.1 on 2023-06-04 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskspace',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskspace',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('taskspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='taskspace.taskspace')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ManyToManyField(to='taskspace.taskgroup'),
        ),
    ]
