# Generated by Django 4.2.1 on 2023-11-18 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
