# Generated by Django 4.2.1 on 2023-11-19 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_shared_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.JSONField(default=list)),
                ('monday', models.JSONField(default=list)),
                ('tuesday', models.JSONField(default=list)),
                ('wednesday', models.JSONField(default=list)),
                ('thursday', models.JSONField(default=list)),
                ('friday', models.JSONField(default=list)),
                ('saturday', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='hours',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='board.boardhour'),
        ),
    ]
